### PR TITLE
illegal.

### PR DESCRIPTION
**Pull request by d1snin**

### CODE REVIEW

**Review by SoNothingMC — APPROVED** [review]
LGTM!

**Comment by ZimnyCat** [comment]
legal

**Comment by d1snin** [comment]
no way

**Comment by ZimnyCat** [comment]
yes way

**Comment by d1snin** [comment]
I wholeheartedly do not support the sexualization of characters and its dissemination.

**Comment by d1snin** [comment]
leave this pr conversation

**Pull request closed without merging**
